# day23_tool_use.py
# Day 23 — Tool Use — Web Search + Calculator
# Sprint: 42-Day Agentic AI Zero-to-Hero
# Date: Friday 15 May 2026
# Stack: CrewAI · OpenAI GPT-4o · DuckDuckGo · Calculator

"""
Day 23 Goal: Add web search tool to researcher agent.
Add calculator tool. Add file writer for report output.

Tools added today:
    1. Web Search Tool    — live DuckDuckGo search
    2. Calculator Tool    — mathematical calculations
    3. File Writer Tool   — saves report output to file

Use Case: Magic Circle law firm — legal fee calculation
    and current rate research for client billing disputes.

GitHub: github.com/sheyiteluwo-ai/agentic-systems-architect-sprint
"""

import os
import json
import math
from dotenv import load_dotenv
from datetime import datetime, timezone

load_dotenv()


# ── Tool Definitions ──────────────────────────────────────────────────────────

def create_tools():
    """
    Creates all three tools wrapped for CrewAI compatibility.
    Returns list of tools ready for agent use.
    """
    from crewai.tools import tool
    from langchain_community.tools import DuckDuckGoSearchRun

    duckduckgo = DuckDuckGoSearchRun()

    # ── Tool 1: Web Search ────────────────────────────────────────────────────
    @tool("Web Search Tool")
    def web_search(query: str) -> str:
        """
        Search the web for current legal and financial information.
        Use for finding current rates, legislation, and case law.
        Input: search query string.
        """
        try:
            result = duckduckgo.run(query)
            return result if result else "No results found for this query."
        except Exception as e:
            return f"Search error: {str(e)}"

    # ── Tool 2: Calculator ────────────────────────────────────────────────────
    @tool("Calculator Tool")
    def calculator(expression: str) -> str:
        """
        Perform mathematical calculations for legal fee analysis.
        Input: a mathematical expression as a string.
        Examples: '150 * 8', '(500 * 0.2) + 1000', '75000 / 12'
        Returns the calculated result as a string.
        """
        try:
            # Safe evaluation — only allow math operations
            allowed = {
                "__builtins__": {},
                "abs": abs, "round": round,
                "min": min, "max": max,
                "pow": pow, "sqrt": math.sqrt,
                "ceil": math.ceil, "floor": math.floor
            }
            result = eval(expression, allowed)
            return f"Result: {result}"
        except Exception as e:
            return f"Calculation error: {str(e)}"

    # ── Tool 3: File Writer ───────────────────────────────────────────────────
    @tool("File Writer Tool")
    def file_writer(content: str) -> str:
        """
        Save report content to a file.
        Input: the full report content as a string.
        Saves to day23_report_output.txt and returns confirmation.
        """
        try:
            filename = "day23_report_output.txt"
            with open(filename, "w", encoding="utf-8") as f:
                f.write(f"DAY 23 — TOOL USE REPORT OUTPUT\n")
                f.write(
                    f"Generated: "
                    f"{datetime.now(timezone.utc).isoformat()}\n"
                )
                f.write("="*65 + "\n\n")
                f.write(content)
            return f"Report saved to {filename} ({len(content)} characters)"
        except Exception as e:
            return f"File write error: {str(e)}"

    return [web_search, calculator, file_writer]


# ── Tool Demo — Without Agents ────────────────────────────────────────────────

def demo_tools_standalone():
    """
    Demonstrates all three tools working independently
    before integrating with agents.
    """
    print("\n── STANDALONE TOOL DEMOS ───────────────────────────────")

    tools = create_tools()
    web_search, calculator, file_writer = tools

    # Web search demo
    print("\n  Tool 1: Web Search")
    result = web_search.run(
        "UK solicitor hourly rates 2024 Magic Circle law firms"
    )
    print(f"  Search result: {result[:200]}...")

    # Calculator demo
    print("\n  Tool 2: Calculator")
    calculations = [
        "150 * 8",
        "500 * 0.2 + 1000",
        "75000 / 12",
        "round(1234567 * 0.025, 2)"
    ]
    for calc in calculations:
        result = calculator.run(calc)
        print(f"  {calc} = {result}")

    # File writer demo
    print("\n  Tool 3: File Writer")
    test_content = (
        "Test report content.\n"
        "This demonstrates the file writer tool.\n"
        "Generated by Day 23 tool use demo."
    )
    result = file_writer.run(test_content)
    print(f"  {result}")


# ── Agent With Tools ──────────────────────────────────────────────────────────

def run_agent_with_tools():
    """
    Runs a legal fee analysis agent equipped with all three tools.

    The agent:
    1. Searches the web for current UK solicitor rates
    2. Uses the calculator to compute fee estimates
    3. Writes the final report to file
    """
    from crewai import Agent, Task, Crew, Process

    print("\n── AGENT WITH TOOLS ────────────────────────────────────")
    print("  Task: UK legal fee analysis for client billing dispute")
    print("  Tools: Web Search + Calculator + File Writer\n")

    tools = create_tools()

    legal_analyst = Agent(
        role="Legal Fee Analyst",
        goal=(
            "Research current UK solicitor billing rates, calculate "
            "fee estimates for a client dispute, and save the analysis "
            "report to file."
        ),
        backstory=(
            "You are a legal costs expert at a Magic Circle law firm. "
            "You help clients understand whether they have been "
            "overbilled. You use web search to find current market "
            "rates, your calculator to verify billing calculations, "
            "and always save your analysis to file."
        ),
        verbose=True,
        allow_delegation=False,
        tools=tools,
        llm="gpt-4o"
    )

    analysis_task = Task(
        description=(
            "A client is disputing a legal bill of £45,000 for 90 hours "
            "of work on a commercial contract matter.\n\n"
            "Your job:\n"
            "1. Search the web for current UK Magic Circle solicitor "
            "hourly rates (2024-2026)\n"
            "2. Use the calculator to check if £45,000 for 90 hours "
            "is reasonable at market rates\n"
            "3. Calculate what the bill should be at market rates\n"
            "4. Write and save a clear analysis report using the "
            "file writer tool\n\n"
            "Be specific with calculations. Show your working."
        ),
        expected_output=(
            "A complete fee analysis including:\n"
            "- Current market hourly rates found via web search\n"
            "- Calculator verification of the disputed bill\n"
            "- Comparison of billed amount vs market rate\n"
            "- Clear recommendation\n"
            "- Confirmation that report was saved to file"
        ),
        agent=legal_analyst
    )

    crew = Crew(
        agents=[legal_analyst],
        tasks=[analysis_task],
        process=Process.sequential,
        verbose=True
    )

    result = crew.kickoff()
    return str(result)


# ── Main Demo ─────────────────────────────────────────────────────────────────

def run_demo():
    print("\n" + "="*65)
    print("  DAY 23 — TOOL USE — WEB SEARCH + CALCULATOR")
    print("  Date: Friday 15 May 2026")
    print("  Tools: Web Search + Calculator + File Writer")
    print("="*65)

    # Step 1: Demo tools standalone
    demo_tools_standalone()

    # Step 2: Run agent with all tools
    print("\n\n" + "="*65)
    print("  RUNNING AGENT WITH ALL THREE TOOLS")
    print("="*65)
    result = run_agent_with_tools()

    # Save summary
    summary = {
        "date": datetime.now(timezone.utc).isoformat(),
        "sprint_day": 23,
        "tools_built": [
            "Web Search Tool (DuckDuckGo)",
            "Calculator Tool (safe eval)",
            "File Writer Tool (saves to .txt)"
        ],
        "agent_task": "UK legal fee analysis for billing dispute",
        "output_preview": result[:500]
    }

    with open("day23_tool_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print("\n" + "="*65)
    print("  DAY 23 COMPLETE — TOOL USE VERIFIED")
    print("="*65)
    print(f"  Tools built:      3 (Search + Calculator + Writer)")
    print(f"  Agent task:       Legal fee dispute analysis")
    print(f"  Report saved:     day23_report_output.txt")
    print(f"  Summary saved:    day23_tool_summary.json")
    print("="*65)

    print("\n  INTERVIEW TALKING POINT:")
    print("  " + "-"*56)
    print("  I gave my agents three tools today — live web search,")
    print("  a safe calculator, and a file writer. The legal fee")
    print("  analyst agent searched for current Magic Circle rates,")
    print("  used the calculator to verify whether a £45,000 bill")
    print("  for 90 hours was reasonable, and saved its analysis")
    print("  to file automatically. Tools transform agents from")
    print("  talkers into doers.")
    print("  " + "-"*56 + "\n")


# ── Entry Point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    run_demo()
